name: 'Deploy Vue.js App to Github Pages'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
inputs:
  username:
    description: 'Your username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your Github token'
    required: true
  gitemail:
    description: 'Your git commit email'
    required: false
    default: 'CI@example.com'
  gitname:
    description: 'Your git commit name'
    required: false
    default: 'CI'
  gitmsg:
    description: 'Your git commit message'
    required: false
    default: 'deploy'
  cname:
    description: 'Your custom domain'
    required: false
    default: 'none'
  useyarn:
    description: 'Use yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: "npm"

      run: |
            if [ true ==  ${{ inputs.useyarn }} ]; then yarn install --frozen-lockfile; else npm ci; fi
            if [ true ==  ${{ inputs.useyarn }} ]; then yarn build; else npm run build --if-present; fi
            cd dist
            ln -s index.html 404.html
            if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi
            git config --global user.email "${{ inputs.gitemail }}"
            git config --global user.name "${{ inputs.gitname }}"
            git init
            git add -A
            git commit -m '${{ inputs.gitmsg }}'
            git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git master:gh-pages
      shell: bash
